// adminService.ts
// Auto-generated by create_backend_structure.py
import 'mongoose';
import {UpdateRoleDepsDTO} from '../Dtos/admin/ChangeRoles.Dto';
import {updateMetadataArray} from '../Repository/GlobalMetadata.Repo'

export const UpdateRoleDepsServ=async (body:UpdateRoleDepsDTO)=>{
  return await updateMetadataArray(body.name,body.data,true);
}
