// adminService.ts
// Auto-generated by create_backend_structure.py
import 'mongoose';
import {UpdateRoleDepsDTO} from '../Dtos/admin/ChangeRoles.Dto.js';
import {upsertMetaData} from '../Repository/GlobalMetadata.Repo.js'

export const UpdateRoleDepsServ=async (body:UpdateRoleDepsDTO)=>{
  return await upsertMetaData(body.name,body.data);
}
